language: go

os:
  - osx

go:
  - "1.12"

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/kr/pty
  - go get github.com/mattn/goveralls
  - go get github.com/ssh-vault/crypto
  - go get github.com/ssh-vault/crypto/aead
  - go get github.com/ssh-vault/crypto/oaep
  - go get github.com/ssh-vault/go-keychain
  - go get github.com/ssh-vault/ssh2pem
  - go get golang.org/x/crypto/ssh/terminal
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - tree /home/travis/gopath/src/github.com/
  - ln -s /home/travis/gopath/src/github.com/zhogov /home/travis/gopath/src/github.com/ssh-vault
  - ls /home/travis/gopath/src/github.com/ssh-vault/
  - ls /home/travis/gopath/src/github.com/zhogov/
  - ls /home/travis/gopath/src/github.com/
  - make build
  - make build-linux

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
